// Mock data for the Roseburg Business Directory mockup
// TODO: fetch from DB — replace with real Prisma/Supabase queries

export type Category = "Business" | "Service" | "Organization";

export interface Business {
  id: string;
  name: string;
  description: string; // max 35 words
  categories: Category[];
  address: string;
  phone: string;
  website: string;
  logoPlaceholder: string; // emoji or initials for mockup
  logoColor: string;       // bg color for logo placeholder
  featured: boolean;
  plan: "monthly" | "annual";
  status: "active" | "paused" | "lapsed";
  lastPayment: string;
  joinedDate: string;
  pendingApproval?: boolean;
}

export const MOCK_BUSINESSES: Business[] = [
  {
    id: "1",
    name: "Riverside Diner",
    description: "Classic American diner on the banks of the South Umpqua. Breakfast served all day, hand-cut steaks, homemade pies, and friendly service since 1987.",
    categories: ["Business"],
    address: "412 W Oak Ave, Roseburg, OR 97470",
    phone: "(541) 672-4400",
    website: "https://example.com",
    logoPlaceholder: "RD",
    logoColor: "#b45309",
    featured: true,
    plan: "annual",
    status: "active",
    lastPayment: "2026-03-01",
    joinedDate: "2025-01-15",
  },
  {
    id: "2",
    name: "Umpqua Plumbing & Heating",
    description: "Licensed plumbing and HVAC contractor serving Douglas County. Same-day service, free estimates, and 24/7 emergency response for residential and commercial clients.",
    categories: ["Service"],
    address: "1820 NE Stephens St, Roseburg, OR 97470",
    phone: "(541) 440-8822",
    website: "https://example.com",
    logoPlaceholder: "UP",
    logoColor: "#0369a1",
    featured: false,
    plan: "monthly",
    status: "active",
    lastPayment: "2026-04-01",
    joinedDate: "2025-04-10",
  },
  {
    id: "3",
    name: "Roseburg Community Church",
    description: "Welcoming congregation in the heart of Roseburg. Sunday services, youth programs, community meals, and outreach initiatives serving Douglas County since 1962.",
    categories: ["Organization"],
    address: "233 SE Washington Ave, Roseburg, OR 97470",
    phone: "(541) 673-1100",
    website: "https://example.com",
    logoPlaceholder: "RC",
    logoColor: "#047857",
    featured: false,
    plan: "annual",
    status: "active",
    lastPayment: "2026-01-01",
    joinedDate: "2025-01-20",
  },
  {
    id: "4",
    name: "Douglas County Roofing Co.",
    description: "Full-service roofing contractor with 20+ years in Douglas County. Residential repairs, new installations, inspections, and storm damage restoration. Free estimates.",
    categories: ["Service"],
    address: "3305 W Harvard Ave, Roseburg, OR 97471",
    phone: "(541) 464-7700",
    website: "https://example.com",
    logoPlaceholder: "DC",
    logoColor: "#0369a1",
    featured: false,
    plan: "monthly",
    status: "active",
    lastPayment: "2026-04-05",
    joinedDate: "2025-06-01",
  },
  {
    id: "5",
    name: "South Umpqua Bakery",
    description: "Artisan breads, pastries, and custom cakes baked fresh daily. Gluten-friendly options, espresso bar, and seasonal specials. A Roseburg morning tradition.",
    categories: ["Business"],
    address: "527 SE Main St, Roseburg, OR 97470",
    phone: "(541) 673-5580",
    website: "https://example.com",
    logoPlaceholder: "SU",
    logoColor: "#b45309",
    featured: true,
    plan: "annual",
    status: "active",
    lastPayment: "2026-02-01",
    joinedDate: "2025-02-28",
  },
  {
    id: "6",
    name: "Mercy Medical Center Auxiliary",
    description: "Volunteer organization supporting Mercy Medical Center with fundraising, patient services, and community health education throughout Douglas County.",
    categories: ["Organization"],
    address: "2700 Stewart Pkwy, Roseburg, OR 97471",
    phone: "(541) 677-2000",
    website: "https://example.com",
    logoPlaceholder: "MM",
    logoColor: "#047857",
    featured: false,
    plan: "annual",
    status: "active",
    lastPayment: "2026-01-15",
    joinedDate: "2025-03-01",
  },
  {
    id: "7",
    name: "Valley Auto Glass",
    description: "Windshield replacement and auto glass repair for all makes and models. Mobile service available throughout Douglas County. Insurance claims handled directly.",
    categories: ["Service"],
    address: "780 NE Garden Valley Blvd, Roseburg, OR 97470",
    phone: "(541) 440-4455",
    website: "https://example.com",
    logoPlaceholder: "VA",
    logoColor: "#0369a1",
    featured: false,
    plan: "monthly",
    status: "paused",
    lastPayment: "2026-03-01",
    joinedDate: "2025-05-10",
  },
  {
    id: "8",
    name: "Timber Ridge Hardware",
    description: "Locally owned hardware store with lumber, tools, paint, and garden supplies. Knowledgeable staff, key cutting, and contractor accounts available.",
    categories: ["Business"],
    address: "1035 SE Stephens St, Roseburg, OR 97470",
    phone: "(541) 672-9900",
    website: "https://example.com",
    logoPlaceholder: "TR",
    logoColor: "#b45309",
    featured: false,
    plan: "monthly",
    status: "active",
    lastPayment: "2026-04-01",
    joinedDate: "2025-07-15",
  },
  {
    id: "9",
    name: "Umpqua Valley Arts Association",
    description: "Nonprofit arts organization hosting gallery shows, workshops, youth programs, and community events celebrating the creative talent of the Umpqua Valley region.",
    categories: ["Organization"],
    address: "1624 W Harvard Ave, Roseburg, OR 97471",
    phone: "(541) 672-2532",
    website: "https://example.com",
    logoPlaceholder: "UV",
    logoColor: "#047857",
    featured: true,
    plan: "annual",
    status: "active",
    lastPayment: "2026-01-01",
    joinedDate: "2025-01-05",
  },
  {
    id: "10",
    name: "Canyon Creek Landscaping",
    description: "Full-service landscaping and lawn maintenance for residential and commercial properties. Irrigation systems, tree trimming, seasonal cleanups, and drought-resistant design.",
    categories: ["Service"],
    address: "4210 Old Highway 99, Roseburg, OR 97470",
    phone: "(541) 660-3344",
    website: "https://example.com",
    logoPlaceholder: "CC",
    logoColor: "#0369a1",
    featured: false,
    plan: "monthly",
    status: "active",
    lastPayment: "2026-04-01",
    joinedDate: "2025-08-20",
  },
  {
    id: "11",
    name: "Roseburg Brewing Co.",
    description: "Craft brewery and taproom with rotating Pacific Northwest ales, lagers, and seasonals. Food trucks on weekends, live music Fridays, and a dog-friendly patio.",
    categories: ["Business"],
    address: "315 SE Jackson St, Roseburg, OR 97470",
    phone: "(541) 900-2288",
    website: "https://example.com",
    logoPlaceholder: "RB",
    logoColor: "#b45309",
    featured: true,
    plan: "annual",
    status: "active",
    lastPayment: "2026-02-15",
    joinedDate: "2025-02-01",
  },
  {
    id: "12",
    name: "Douglas Family Dental",
    description: "Comprehensive dental care for patients of all ages. Cleanings, fillings, cosmetic dentistry, orthodontics, and emergency appointments. New patients always welcome.",
    categories: ["Service", "Business"],
    address: "2850 NW Stewart Pkwy Ste 200, Roseburg, OR 97471",
    phone: "(541) 673-8800",
    website: "https://example.com",
    logoPlaceholder: "DF",
    logoColor: "#0369a1",
    featured: false,
    plan: "annual",
    status: "active",
    lastPayment: "2026-03-01",
    joinedDate: "2025-03-15",
  },
  {
    id: "13",
    name: "Roseburg Habitat for Humanity",
    description: "Building strength, stability, and self-reliance through affordable homeownership in Douglas County. Volunteers welcome. ReStore open to the public Tuesday–Saturday.",
    categories: ["Organization"],
    address: "565 SE Pine St, Roseburg, OR 97470",
    phone: "(541) 673-3636",
    website: "https://example.com",
    logoPlaceholder: "RH",
    logoColor: "#047857",
    featured: false,
    plan: "annual",
    status: "active",
    lastPayment: "2026-01-01",
    joinedDate: "2025-01-10",
    pendingApproval: false,
  },
  {
    id: "14",
    name: "Green Valley Pet Clinic",
    description: "Full-service veterinary clinic for dogs, cats, and small animals. Wellness exams, vaccinations, surgery, dental care, and urgent appointments in Roseburg.",
    categories: ["Service", "Business"],
    address: "705 NW Garden Valley Blvd, Roseburg, OR 97470",
    phone: "(541) 672-3377",
    website: "https://example.com",
    logoPlaceholder: "GV",
    logoColor: "#047857",
    featured: false,
    plan: "monthly",
    status: "lapsed",
    lastPayment: "2026-02-01",
    joinedDate: "2025-09-01",
  },
  {
    id: "15",
    name: "Umpqua Bank — Roseburg Main Branch",
    description: "Full-service community bank offering checking, savings, home loans, business banking, and financial planning. Serving Roseburg and Douglas County since 1953.",
    categories: ["Business"],
    address: "445 SE Cass Ave, Roseburg, OR 97470",
    phone: "(541) 440-4000",
    website: "https://example.com",
    logoPlaceholder: "UB",
    logoColor: "#b45309",
    featured: false,
    plan: "annual",
    status: "active",
    lastPayment: "2026-01-15",
    joinedDate: "2025-01-01",
    pendingApproval: true,
  },
];

// Mock news posts for the feed preview page
export interface NewsPost {
  id: string;
  headline: string;
  excerpt: string;
  category: string;
  readTime: string;
  publishedAt: string;
  imageColor: string;
}

export const MOCK_NEWS_POSTS: NewsPost[] = [
  { id: "n1", headline: "Douglas County commissioners approve new fire district budget for 2026", excerpt: "The board voted 4–1 Tuesday to increase the fire district levy, funding two new engine companies and expanded wildfire mitigation work across the county.", category: "Government", readTime: "3 min read", publishedAt: "2 hours ago", imageColor: "#e5e7eb" },
  { id: "n2", headline: "Roseburg High School girls basketball advances to state semifinals", excerpt: "The Indians defeated Grants Pass 58–44 on the road Friday, booking a trip to the OSAA 5A state tournament for the first time since 2019.", category: "Sports", readTime: "2 min read", publishedAt: "4 hours ago", imageColor: "#e5e7eb" },
  { id: "n3", headline: "New urgent care clinic to open on Garden Valley Boulevard this spring", excerpt: "OregonPath Health announced it will open a 6,000-square-foot urgent care and primary care facility in Roseburg's northwest corridor in May.", category: "Healthcare", readTime: "4 min read", publishedAt: "6 hours ago", imageColor: "#e5e7eb" },
  { id: "n4", headline: "Wildfire smoke impacts air quality across Umpqua Valley this week", excerpt: "The Oregon DEQ issued an air quality advisory for Douglas County as smoke from the Cow Creek fire to the east drifted into the valley Monday.", category: "Wildfires", readTime: "3 min read", publishedAt: "8 hours ago", imageColor: "#e5e7eb" },
  { id: "n5", headline: "City council weighs downtown parking changes ahead of summer events", excerpt: "A proposal to convert two-hour parking zones near the fairgrounds to paid parking during events drew mixed reactions from business owners.", category: "City Council", readTime: "5 min read", publishedAt: "Yesterday", imageColor: "#e5e7eb" },
  { id: "n6", headline: "Roseburg school district hires new superintendent from Eugene", excerpt: "Dr. Maria Chen, previously assistant superintendent at Eugene 4J, will take the helm at Roseburg Public Schools starting July 1.", category: "Education", readTime: "3 min read", publishedAt: "Yesterday", imageColor: "#e5e7eb" },
  { id: "n7", headline: "South Umpqua River salmon counts show modest improvement in 2025", excerpt: "Fall Chinook returns to the South Umpqua were up 18% over last year, a cautious sign of recovery for a watershed hit hard by drought and temperature.", category: "Environment", readTime: "4 min read", publishedAt: "2 days ago", imageColor: "#e5e7eb" },
  { id: "n8", headline: "Douglas County Fair sets attendance record with 42,000 visitors", excerpt: "This year's fair drew record crowds despite competition from a Salem event on the same weekend, with carnival rides and the rodeo selling out.", category: "Community", readTime: "2 min read", publishedAt: "3 days ago", imageColor: "#e5e7eb" },
  { id: "n9", headline: "Roseburg VA Clinic expands mental health services for veterans", excerpt: "The Roseburg VA expanded its outpatient mental health clinic, adding three therapists and extending hours to Saturdays starting this month.", category: "Healthcare", readTime: "3 min read", publishedAt: "3 days ago", imageColor: "#e5e7eb" },
  { id: "n10", headline: "Local artist mural approved for downtown Roseburg transit center", excerpt: "The Roseburg Area Chamber selected a design by local muralist Juan Delgado for the new 40-foot exterior wall at the downtown transit hub.", category: "Arts", readTime: "2 min read", publishedAt: "4 days ago", imageColor: "#e5e7eb" },
];
